version: "2"

services:
  nginx:
    container_name: nginx-deneme
    image: nginx:latest
    ports:
      - 1080:80
      - 1088:88
    volumes:
      - ./www/server80:/usr/share/nginx/server80
      - ./www/changelogs:/usr/share/nginx/changelogs
      - ./nginx.conf:/etc/nginx/conf/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
#      - ./changelogs:/var/repositories/changelogs

